### ISSUE TITLE
importlib-metadata version conflicts

### ISSUE THREAD

**Issue by federicaunipi** [RealVNF/coord-sim#203]
I have tried installing coord-sim (from https://github.com/RealVNF/coord-sim) but I have some problems with conflicting versions of import-lib metadata.

More precisely, the error message is 

markdown 3.3.6 has requirement importlib-metadata>=4.4; python_version < "3.10", but you'll have importlib-metadata 4.2.0 which is incompatible.

when I install importlib-metadata 4.4.0 I obtain the following error message

flake8 4.0.1 has requirement importlib-metadata<4.3; python_version < "3.8", but you'll have importlib-metadata 4.4.0 which is incompatible

thank you in advance for any support you can provide

**Comment by AlexPasqua** [comment]
@federicaunipi,
I had, and solved, the same issue.

[`flake8`](https://flake8.pycqa.org/en/latest/) is a Python package for the style formatting of the code, therefore it's not really a "core component" of the project.
In my case it was sufficient to comment the line about `flake8` in the file [`setup.py`](https://github.com/RealVNF/coord-sim/blob/6c3da716c6c70aed6ee93b7c4ad703c6a4316807/setup.py), like this:
```
test_requirements = [
    # 'flake8',
    'nose2'
]
```
Note that in [`requirements.txt`](https://github.com/RealVNF/coord-sim/blob/6c3da716c6c70aed6ee93b7c4ad703c6a4316807/requirements.txt) it is listed the repository [RealVNF/common-utils](https://github.com/RealVNF/common-utils), which contains as well a [`setup.py`](https://github.com/RealVNF/common-utils/blob/bdfb7a101f38e7d9faa21ae973e650d74ec514aa/setup.py) listing again `flake8`. I commented that line as well.

One last note: in my case I was getting a "connection timed out" when performing `python -m pip install -r requirements.txt` because it wasn't possible to connect to the repository of [RealVNF/common-utils](https://github.com/RealVNF/common-utils) to be downloaded in the Python virtual environment of the project. To solve this issue I had to do the following 2 steps:
1. Perform a manual `git clone` of [RealVNF/common-utils](https://github.com/RealVNF/common-utils) in `coord-sim/<name_of_virtualenv>/src/`
2. Modify the first line in the file [`requirements.txt`](https://github.com/RealVNF/coord-sim/blob/6c3da716c6c70aed6ee93b7c4ad703c6a4316807/requirements.txt) (of [coord-sim](https://github.com/RealVNF/coord-sim)), changing it from
```
--editable git://github.com/RealVNF/common-utils#egg=common-utils
```
to
```
--editable /absolute/path/to/coord-sim/<name_of_virtualenv>/common-utils/
```
(I haven't tried with a relative path, it might work as well)

**Comment by stefanbschneider** [comment]
Hi, thanks for using (or trying to use) `coord-sim` and for reporting the issue (@federicaunipi ) + for helping out (@AlexPasqua ).

I just created a PR to upgrade some of the dependencies and also fix the installation of the external `coord-sim` dependency, which fixed any install issues for me.

Would be great if you could try again with a fresh Python 3.6 virtualenv. Please let me know if the setup works smoothly now or if you still run into problems.

**Comment by AlexPasqua** [comment]
@stefanbschneider 
> Would be great if you could try again with a fresh Python 3.6 virtualenv. Please let me know if the setup works smoothly now or if you still run into problems.

Now everything installs smoothly, thank you! :)
